### ISSUE TITLE
error on pdb writing

### ISSUE THREAD

**Issue by Pellarin** [salilab/imp_tutorial#25]
with imp 2.5.0

```
--- frame 9 score 428899.18561 
--- writing coordinates
^CTraceback (most recent call last):
  File "modeling.py", line 234, in <module>
    mc1.execute_macro()
  File "/usr/lib/python2.7/dist-packages/IMP/pmi/macros.py", line 377, in execute_macro
    output.write_pdb_best_scoring(score)
  File "/usr/lib/python2.7/dist-packages/IMP/pmi/output.py", line 307, in write_pdb_best_scoring
    self.write_pdb(filetoadd, appendmode=False)
  File "/usr/lib/python2.7/dist-packages/IMP/pmi/output.py", line 135, in write_pdb
    chain_id, residue_index,' ',1.00,radius))
  File "/usr/lib/python2.7/dist-packages/IMP/atom/__init__.py", line 11029, in get_pdb_string
    return _IMP_atom.get_pdb_string(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'get_pdb_string'.
  Possible C/C++ prototypes are:
    IMP::atom::get_pdb_string(IMP::algebra::Vector3D const &,int,IMP::atom::AtomType,IMP::atom::ResidueType,char,int,char,double,double,IMP::atom::Element)
    IMP::atom::get_pdb_string(IMP::algebra::Vector3D const &,int,IMP::atom::AtomType,IMP::atom::ResidueType,char,int,char,double,double)
    IMP::atom::get_pdb_string(IMP::algebra::Vector3D const &,int,IMP::atom::AtomType,IMP::atom::ResidueType,char,int,char,double)
    IMP::atom::get_pdb_string(IMP::algebra::Vector3D const &,int,IMP::atom::AtomType,IMP::atom::ResidueType,char,int,char)
    IMP::atom::get_pdb_string(IMP::algebra::Vector3D const &,int,IMP::atom::AtomType,IMP::atom::ResidueType,char,int)
    IMP::atom::get_pdb_string(IMP::algebra::Vector3D const &,int,IMP::atom::AtomType,IMP::atom::ResidueType,char)
    IMP::atom::get_pdb_string(IMP::algebra::Vector3D const &,int,IMP::atom::AtomType,IMP::atom::ResidueType)
    IMP::atom::get_pdb_string(IMP::algebra::Vector3D const &,int,IMP::atom::AtomType)
    IMP::atom::get_pdb_string(IMP::algebra::Vector3D const &,int)
    IMP::atom::get_pdb_string(IMP::algebra::Vector3D const &)

WARNING  Object "linker_restraints" was never used. See the IMP::Object documentation for an explanation.
```

**Comment by benmwebb** [comment]
Are you sure this is with unmodified IMP 2.5.0 and an unmodified tutorial? The tutorial works fine with 2.5.0 for me (and is tested, as per http://integrativemodeling.org/systems/?build=29&sys=7). And from that traceback, it looks like PMI is calling the right function (the 2nd prototype in the list shown).

**Comment by Pellarin** [comment]
Thanks! I'm reporting an issue from an user who says it was 2.5.0. I'll check with him if the version is OK.

**Comment by benmwebb** [comment]
User reports this is on an Ubuntu 14.04.3 64 bit system using the binary `.deb` package.

**Comment by benmwebb** [comment]
Cannot reproduce; works fine for me on Ubuntu 14.04:

    $ lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 14.04.3 LTS
    Release:	14.04
    Codename:	trusty
    $ tail -1 /etc/apt/sources.list
    deb http://integrativemodeling.org/latest/download trusty/
    $ sudo apt-get install imp
    [...]
    $ git clone https://github.com/salilab/imp_tutorial.git
    [...]
    $ cd imp_tutorial/rnapolii/modeling/
    $ python modeling.py --test
    [lots of output, ending successfully]

If you did something different, let me know.
