### ISSUE TITLE
Analysis does not work on precalculated trajectory

### ISSUE THREAD

**Issue by benmwebb** [salilab/imp_tutorial#33]
"However, when I try to do the analysis on the precalculated trajectory downloaded from here:

https://salilab.org/ftp/tutorials/imp/rnapolii/results.tar.gz

I get the error below.  Any idea what is going on?"

```
(imp) @ziggy ~/work/imp_tutorial/rnapolii/analysis] python clustering.py
...
Traceback (most recent call last):
  File "/Users/max/work/imp_tutorial/rnapolii/analysis/clustering.py", line 51, in <module>
    mc.clustering(
  File "/usr/local/anaconda3/envs/imp/lib/python3.10/site-packages/IMP/pmi/macros.py", line 1540, in clustering
    IMP.core.transform(IMP.core.XYZ(p),
  File "/usr/local/anaconda3/envs/imp/lib/python3.10/site-packages/IMP/core/__init__.py", line 7867, in transform
    return _IMP_core.transform(*args)
_IMP_kernel.UsageException: Usage check failure: Particle is also a RigidBody, so this function would do the wrong thing; decorate your Particle as a RigidBody instead and call transform(RigidBody a, const algebra::Transformation3D &tr)
```

May be a consequence of #26.

**Comment by benmwebb** [comment]
Fix by replacing precomputed trajectory with that from Max's repo, and test in 321a8d0f499d018747970ab3a5a16de49cffa8b5.
